apiVersion: v1
kind: Service
metadata:
  name: apontamento-horas-front-dev-svc
  namespace: idg-dev
  labels:
    app: apontamento-horas-front-dev
spec:
  type: NodePort
  selector:
    app: apontamento-horas-front-dev
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 3000
